name: Update Distribution

on:
  schedule:
  - cron:  "*/20 * * * *"
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BASE_FILES_URL: https://raw.githubusercontent.com/theypsilon-test/delme/%s/
      DB_JSON_NAME: db.json
      DB_ID: distribution_mister
      DB_URL: https://raw.githubusercontent.com/theypsilon-test/delme/main/db.json.zip
      ZIPS_CONFIG: ./.github/zips_config.json
      LINUX_GITHUB_REPOSITORY: MiSTer-devel/SD-Installer-Win64_MiSTer

    steps:
    - uses: actions/checkout@v3
      with:
        ref: develop

    - name: Install apt-get utilities
      run: sudo apt-get install sharutils

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Set Git User
      run: |
        git config --global user.email "theypsilon@gmail.com"
        git config --global user.name "The CI/CD Bot"

    - name: Download Distribution
      run: ./.github/download_distribution.py .

    - name: Validate Distribution
      run: |
        FILES=$(find . -type f | wc -l)
        echo "FILES: ${FILES}"
        if (( ${FILES} < 13000 )) ; then
          echo "Not enough files!"
          exit 1
        fi

    - name: Commit Distribution
      run: ./.github/commit_distribution.sh

    - name: Build Database
      run: ./.github/db_operator.py build .

    - name: New Database Exists?
      id: db_exists
      run: if [ -f "${DB_JSON_NAME}" ] ; then echo "new_db=true" >> "${GITHUB_OUTPUT}" ; fi

    - name: Test Database
      if: steps.db_exists.outputs.new_db == 'true' 
      run: ./.github/test_database.sh

    - name: Push Database
      if: steps.db_exists.outputs.new_db == 'true' 
      run: ./.github/push_database.sh
